baseURL                          = "https://www.anoushkajoglekar.com/"   # Your domain name. Must end with "/"
#baseURL                          = "https://noush-personal-website.netlify.app/"
theme = "hugo-theme-introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
googleAnalytics                 = "UA-123-45"                     # https://gohugo.io/templates/internal/#google-analytics
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyurls = true

[params]
    themeStyle                   = "light"                  # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    # email                        = "[E-mail](mailto:anj2026@med.cornell.edu) is the quickest way to get me"   # E-mail address for contact section
    # customCSS                  = ["foo.css"]             # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        numberOfPublicationsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "America/New_York"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-US"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three
    [params.publications]
        useTwoColumns            = true                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        github                   = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/noush_joglekar"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:anj2026@med.cornell.edu"  # For a direct email link, use "mailto:test@example.org".
        icon = "envelope" # icon name without the 'fa-'
        icon_pack = "fas"
    [[params.social]]
        url   = "https://github.com/noush-joglekar/"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://linkedin.com/in/anoushka-joglekar"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://scholar.google.com/citations?user=zH6U8uIAAAAJ&hl=en"
        icon  = "user-graduate" # icon name without the 'fa-'
        icon_pack = "fas"


[[menu.main]]
   name    = "Home"
   url     = "/"
   weight  = 10
[[menu.main]]
   name    = "Posts"
   url     = "/blog/"
   weight  = 50
[[menu.main]]
   name    = "Publications"
   url     = "/publications/"
   weight  = 30
[[menu.main]]
   name    = "CV"
   url     = "/cv/aj_cv.html"
   weight  = 60
[[menu.main]]
   name    = "Projects"
   url     = "/projects/"
   weight  = 40

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "friendly"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Anoushka"
        [languages.en.params]
            description  = "Personal website"   # Max 160 characters show in search results
            footerText   = "Made with R package [blogdown](https://bookdown.org/yihui/blogdown/)"  # Text to override default footer text (markdown allowed)
